binary_sensor:

  - id: zone1
    name: Garage Service Door
    pin:
      number: $zone1
      mode: INPUT_PULLUP
    platform: gpio
color:
  - id: my_black
    red: 100%
    green: 100%
    blue: 100%
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led
