binary_sensor:

  - id: zone8
    name: Tonys Room  
    pin:
      number: $zone8
      mode: INPUT_PULLUP
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led
