binary_sensor:

  - id: zone9
    name: Garage/Basement Door  
    pin:
      number: $zone9
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led
